// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/199acf46b3b6c8e047417df20e551719c5c4979d/supertest-as-promised/supertest-as-promised.d.ts
declare module "supertest-as-promised" {
  import * as supertest from "supertest";
  import * as supersgent from "superagent";
  import { SuperTest, Response } from "supertest";
  import * as PromiseBlurbird from "bluebird";

  function supertestAsPromised(app: any): SuperTest<supertestAsPromised.Test>;

  namespace supertestAsPromised {
    interface Request extends supertest.Request {
    }

    interface Response extends supertest.Response {
    }

    interface Test extends supertest.Test, supersgent.Request {
      toPromise(): PromiseBlurbird<Response>;
    }

    function agent(app?: any): SuperTest<Test>;

    interface SuperTest<T> extends supertest.SuperTest<T> {
    }
  }
  export = supertestAsPromised

}
